# Configuration of Academia
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Aquainnis"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://aquainnis.com"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; {year} Aquainnis Pty Ltd"

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = "" # example: UA-123456-78 or G-XXXXXXXXXX, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en

############################
## Advanced options below ##
############################

# Name of Academia theme folder in `themes/`.
theme = "academia-hugo"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

pagination.pagerSize = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Permalinks for different content types
[permalinks]
  news = "/news/:year/:month/:slug/"
  projects = "/projects/:slug/"
  case-studies = "/case-studies/:slug/"
  services = "/services/:slug/"

[services]
# Enable comments by entering your Disqus shortname
[services.disqus]
# Shortname = "themefisher-template" # DISABLED - we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/

# Build
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure modern Markdown rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      linkify = true
      strikethrough = true
      table = true
      taskList = true
  [markup.highlight]
    style = "github"
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "Lanczos"
  quality = 90
  anchor = "Smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
  service_type = "service_types"
  project_type = "project_types"

# Section configuration - maps folder names to content types
[[cascade]]
  _target.path = "/publications/**"
  type = "publication"

# Caches
[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
